{
  const autosDB = [
    {
      ID: 1,
      Precio: 25000,
      Marca: "Ford",
      Modelo: "Mustang",
      NombreDelVehículo: "Mustang GT 1967",
      AñoDelVehículo: 1967,
      CantidadDePuertas: 2,
      Categoría: "Muscle Car",
      EnOferta: true,
      Descuento: 2000,
    },
    {
      ID: 2,
      Precio: 22000,
      Marca: "Chevrolet",
      Modelo: "Camaro",
      NombreDelVehículo: "Camaro SS 1969",
      AñoDelVehículo: 1969,
      CantidadDePuertas: 2,
      Categoría: "Muscle Car",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 3,
      Precio: 35000,
      Marca: "Jaguar",
      Modelo: "E-Type",
      NombreDelVehículo: "Jaguar E-Type Serie 1",
      AñoDelVehículo: 1961,
      CantidadDePuertas: 2,
      Categoría: "Deportivo",
      EnOferta: true,
      Descuento: 3000,
    },
    {
      ID: 4,
      Precio: 18000,
      Marca: "Volkswagen",
      Modelo: "Beetle",
      NombreDelVehículo: "Volkswagen Beetle 1967",
      AñoDelVehículo: 1967,
      CantidadDePuertas: 2,
      Categoría: "Económico",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 5,
      Precio: 28000,
      Marca: "Chevrolet",
      Modelo: "Impala",
      NombreDelVehículo: "Chevrolet Impala 1958",
      AñoDelVehículo: 1958,
      CantidadDePuertas: 4,
      Categoría: "Clásico",
      EnOferta: true,
      Descuento: 2500,
    },
    {
      ID: 6,
      Precio: 20000,
      Marca: "Porsche",
      Modelo: "911",
      NombreDelVehículo: "Porsche 911 1964",
      AñoDelVehículo: 1964,
      CantidadDePuertas: 2,
      Categoría: "Deportivo",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 7,
      Precio: 32000,
      Marca: "Mercedes-Benz",
      Modelo: "300SL",
      NombreDelVehículo: "Mercedes-Benz 300SL 1954",
      AñoDelVehículo: 1954,
      CantidadDePuertas: 2,
      Categoría: "Lujo",
      EnOferta: true,
      Descuento: 2800,
    },
    {
      ID: 8,
      Precio: 19000,
      Marca: "Ferrari",
      Modelo: "250 GTO",
      NombreDelVehículo: "Ferrari 250 GTO 1962",
      AñoDelVehículo: 1962,
      CantidadDePuertas: 2,
      Categoría: "Deportivo",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 9,
      Precio: 40000,
      Marca: "Aston Martin",
      Modelo: "DB5",
      NombreDelVehículo: "Aston Martin DB5 1963",
      AñoDelVehículo: 1963,
      CantidadDePuertas: 2,
      Categoría: "Lujo",
      EnOferta: true,
      Descuento: 3500,
    },
    {
      ID: 10,
      Precio: 21000,
      Marca: "Chevrolet",
      Modelo: "Bel Air",
      NombreDelVehículo: "Chevrolet Bel Air 1957",
      AñoDelVehículo: 1957,
      CantidadDePuertas: 2,
      Categoría: "Clásico",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 11,
      Precio: 26000,
      Marca: "Plymouth",
      Modelo: "Road Runner",
      NombreDelVehículo: "Plymouth Road Runner 1968",
      AñoDelVehículo: 1968,
      CantidadDePuertas: 2,
      Categoría: "Muscle Car",
      EnOferta: true,
      Descuento: 2200,
    },
    {
      ID: 12,
      Precio: 23000,
      Marca: "Cadillac",
      Modelo: "Eldorado",
      NombreDelVehículo: "Cadillac Eldorado 1959",
      AñoDelVehículo: 1959,
      CantidadDePuertas: 2,
      Categoría: "Lujo",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 13,
      Precio: 29000,
      Marca: "Shelby",
      Modelo: "Cobra",
      NombreDelVehículo: "Shelby Cobra 1965",
      AñoDelVehículo: 1965,
      CantidadDePuertas: 2,
      Categoría: "Deportivo",
      EnOferta: true,
      Descuento: 2600,
    },
    {
      ID: 14,
      Precio: 24000,
      Marca: "Pontiac",
      Modelo: "GTO",
      NombreDelVehículo: "Pontiac GTO 1969",
      AñoDelVehículo: 1969,
      CantidadVePuertas: 2,
      Categoría: "Muscle Car",
      EnOferta: false,
      Descuento: 0,
    },
    {
      ID: 15,
      Precio: 31000,
      Marca: "Jaguar",
      Modelo: "XK-E",
      NombreDelVehículo: "Jaguar XK-E 1961",
      AñoDelVehículo: 1961,
      CantidadDePuertas: 2,
      Categoría: "Deportivo",
      EnOferta: "true",
      Descuento: "2700",
    },
  ];
}

window.addEventListener("load", (event) => {
  main();
});
